### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1005]
Let's pick a default template to style our emails going out.

Ideas: https://mailchimp.com/features/email-templates/

Engineering Notes:
Also a good simple template: https://github.com/leemunroe/responsive-html-email-template
Probably need to inline styles: https://github.com/Automattic/juice

**Comment by nolanpro** [comment]
@velkymx We can include bootstrap ok in mail trap:

![image](https://user-images.githubusercontent.com/2546850/50526867-a8d02c80-0a99-11e9-92d3-d36d9cd8213c.png)


The problem is with google, it doesn't even show it:


![image](https://user-images.githubusercontent.com/2546850/50526875-b685b200-0a99-11e9-8af2-86837a4e36b0.png)


See https://emaildesign.beefree.io/2016/03/prevent-gmail-clipping-email/

When you click on "view entire message" it works but gmail has changed the bootstrap CSS. Notice how the left and right columns don't work.


![image](https://user-images.githubusercontent.com/2546850/50526886-c69d9180-0a99-11e9-90c1-d9f14bbee61b.png)


It also increases our email size from 1kb to 150kb but maybe thats not a problem. But still, it appears gmail will *not* display the message if bootstrap is included.

David decided to remove it and only include a subset: https://github.com/caleeli/bpm-package-email-connector/commit/21f492e2d1633c1d0e3af73186157bdd6eed75f8

This helped and Gmail was OK with it


![image](https://user-images.githubusercontent.com/2546850/50527000-517e8c00-0a9a-11e9-8606-5635b71fb564.png)


But now the images are not showing. Is there a way around that? We will also need to include the styles for the buttons, etc that the template uses.

One solution might be to run the entire email, including bootstrap, through something like https://github.com/Automattic/juice but i haven't looked into how difficult that would be or if it would even work.

**Comment by nolanpro** [comment]
@velkymx  Better, but still looks like this. Seems like simplest solution is to include more subsets like for buttons. Also because gmails doesn't allow for things like negative margins (use for rows) we'll need some workaround in the subset.

![image](https://user-images.githubusercontent.com/2546850/50527262-2006c000-0a9c-11e9-8bfb-4fe15ef20d76.png)

**Comment by velkymx** [comment]
I can throw out bootstrap and make it all 100% HTML with tables and stuff.

**Comment by nolanpro** [comment]
@velkymx that should work much better
