### ISSUE TITLE
Send email task does not work

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#1113]
When a flow reaches the new Send Email task, emails are not sending, and thus the request just hangs. RunServiceTask job shows 'failed'. clicking the link shows error (on the Admin queue).

**Comment by velkymx** [comment]
Related to #1116

**Comment by nolanpro** [comment]
@ryancooley I found added `QUEUE_DRIVER=sync` to your .env is helpful in debugging these issues. It temporarily takes the queue out of the equation for debugging

**Comment by ryancooley** [comment]
@nolanpro Thanks! The queue has definitely been a bit troublesome with this issue so that's really helpful.

**Comment by ryancooley** [comment]
@josemaldonad0 When you receive this error, have you configured any particular mail settings in your .env?

**Comment by nolanpro** [comment]
@josemaldonad0 @ryancooley The easiest way to test is by creating a free account with Mailtrap.io. Then it will give you info to fill in like this: 
![image](https://user-images.githubusercontent.com/2546850/50614639-6e4e0180-0e96-11e9-85ab-3abece2a8d8e.png)

**Comment by nolanpro** [comment]
Part of this issue is to get our packages to install as seamlessly as possible. Currently you need to run 3 seperate commands after you install this package
- `php artisan vendor:publish --tag=bpm-package-email-connector --force`
- `php artisan db:seed --class="ProcessMaker\Packages\Connectors\Email\Seeds\EmailSendSeeder"`
- `php artisan queue:restart` (needed for the workers to pickup changes)

It would be great if these could run automatically after the composer install but composer does not support this: https://github.com/composer/composer/issues/1193

@velkymx @tdondich suggestions? Currently the only way is to give the user instructions to run those commands. I suppose we could build our own dependency runner thing just for bpm4 packages.
