### ISSUE TITLE
Upgrade Babel 7

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1334]
Everything needs to be tested.

**Comment by velkymx** [comment]
Do we need this if we use Monaco editor? 

https://github.com/ProcessMaker/vue-form-elements/issues/14

**Comment by nolanpro** [comment]
@caleeli got this working in feature/1334b
- I did this in a separate branch because your branch had other stuff in it like TimerExpression, etc.
- I kept your package.json but do you think everything should be under devDependencies? I think that's only for stuff not used after we deploy. We definitely need things like Vue and bootstrap-vue
- Works fine as long as we don't extract any modules as chunks (bug in laravel-mix: https://github.com/JeffreyWay/laravel-mix/issues/1889)
- Using latest vue-form-builder and modeler

Try it out and let me know if it works on your end. I'm using npm version 6.4.1

**Comment by caleeli** [comment]
Ohh about the timer event I was adding them for testing proposes because the version 0.4.0 comes with timer events (But yes the lines where they are registered could be removed).
About the dev and non dev, yes absolutely we should move the ones that should be part of the production build.

**Comment by velkymx** [comment]
After talking this over more, this seems to be a nice to have vs a must have. I'm going to remove it from the sprint.
