### ISSUE TITLE
Create Variable Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#174]
Implement the screen attached as a modal. 

<img width="1117" alt="screenshot 2018-05-24 11 05 19" src="https://user-images.githubusercontent.com/535300/40503259-5f314742-5f42-11e8-80bd-6d45bc566fe5.png">

App link: zpl://screen?sid=5af3110bce944c183dfdb018&pid=5a872c6ffc8c7ad639253eb9

**Comment by meadrat** [comment]
@milaendo this is the current version of the modal- its left aligned instead of centered - in case you didn't see the difference in Zeplin. https://zpl.io/2y7X0Qo 
<img width="369" alt="screen shot 2018-06-08 at 8 06 13 am" src="https://user-images.githubusercontent.com/39599643/41165605-eeb288c0-6af2-11e8-98c9-0a56a97bcf4a.png">

**Comment by milaendo** [comment]
@velkymx do you want this updated in this ticket, or another ticket to update?
