### ISSUE TITLE
Create Message Type Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#175]
<img width="1084" alt="screenshot 2018-05-24 11 08 13" src="https://user-images.githubusercontent.com/535300/40503400-cc65aad8-5f42-11e8-83ec-42e3762a47d9.png">

This is ready for development.

App link: zpl://screen?sid=5af310f2c97b185142ecc3df&pid=5a872c6ffc8c7ad639253eb9

https://processmaker.atlassian.net/browse/PMUI-140

**Comment by meadrat** [comment]
@KillahDillah this is the current version of the modal- its left aligned instead of centered - in case you didn't see the difference in Zeplin. 
<img width="360" alt="screen shot 2018-06-08 at 7 58 33 am" src="https://user-images.githubusercontent.com/39599643/41165170-d3099268-6af1-11e8-9534-fa6d791a58ca.png">
https://zpl.io/2pdmXYo

**Comment by KillahDillah** [comment]
https://github.com/ProcessMaker/bpm/pull/261

**Comment by velkymx** [comment]
This is merged
