### ISSUE TITLE
Enhance statuses/enum management 

### ISSUE THREAD

**Issue by devmsh** [ProcessMaker/bpm#913]
I'm really impressed by your decision to redevelop ProcessMaker based on Laravel, and I think it will give the project a very big jump. 

I review the current source code, and I'm interested to contribute with you. If the idea is initially accepted, I will submit a PR.

Are you open to replace the textual statuses enum values using [Laravel Enum](https://laravel-news.com/laravel-enum-package) package?

This can enhance Migrations, Factories, Models, and Validation Rules, Test statuses related code.

Regards,

**Comment by tdondich** [comment]
Hi @devmsh and thanks for reaching out.  Which specific textual status enum values are you looking at? It might be good to see an initial PR with some tests updated that shows it's usage.  We're open to ideas!

Some textual enum values such as Screen Types cannot be based off Laravel Enum because ProcessMaker packages may/could provide new types, so we don't want to force them to a static set of enum values.
